### ISSUE TITLE
hi,can you tell me how to get the msra-b dataset?

### ISSUE THREAD

**Issue by zerowfz** [Andrew-Qibin/DSS#11]
I tried to reproduce the result,but unfortunately I got lower grades with training on the MSRA10K dataset.so i want to train on the the msra-b dataset as you do,but i only get the groundtruth of msra-b,could you provide me the msra-b dataset? thank you very much!

**Comment by houqb** [comment]
Now, I have provided the dataset. You may also find it here (http://mmcheng.net/msra10k/)
