### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by scL18** [Andrew-Qibin/DSS#13]
Does DSS support window&caffe? And can I know the requirements of cudnn version?

**Comment by luyunxi** [comment]
你好，当运行ipython notebook DSS-tutorial.ipynb时报错AttributeError: 'numpy.ndarray' object has no attribute 'mask'，将问有类似的问题出现吗

**Comment by houqb** [comment]
I think it does. After all, windows version caffe provides all the layers we need.
I use cudnn 8.0. If you met any problems about cudnn, you can ban it by setting USE_CUDNN to 0 in either Makefile.config or CMakeLists.txt.

**Comment by houqb** [comment]
@luyunxi  seems weird. Never met before, sorry.
