### ISSUE TITLE
how to compute the processing time (0.08s) of  an image of size 400×300

### ISSUE THREAD

**Issue by Sucran** [Andrew-Qibin/DSS#16]
I had read many CVPR2017 paper related to saliency detection, your model and NLDF(Non-Local Deep Features for Salient Object Detection) all say the processing time == 0.08s, but the model and DL framwork(TF vs Caffe) are different, which should cause a bit different. This makes me confused.
Can you upload an simple ipynb file to explain how the 0.08s to be computed ? or just tell me your method if it's easy to implement.
Thank you very much.

**Comment by houqb** [comment]
Actually it is a approximate value. You can test your model on some dataset, say MSRA-B, and report the average time on each image. It seems the speed is not that important.

**Comment by houqb** [comment]
If you want an exact value, we can resize all the images of some dataset to size 300 * 400.
