### ISSUE TITLE
The groundtruth of result data in your Baiduyun could not reproduce your result   

### ISSUE THREAD

**Issue by Sucran** [Andrew-Qibin/DSS#18]
I download your result data, code and model in order to reproduce your result, and I really done
But I use the ECSSD groudtruth in your result data could not reproduce your result, so I change to the original ECSSD dataset's groudtruth and I reproduced.
There are some differences between your gt and original gt dataset, such as data type and files' storage space.  
So can you check the gt and give the right one ?
I found difference in SOD, PASCAL-S and ECSSD, thank you!

**Comment by Xavierman** [comment]
Maybe that's not gt, they are the results of DSS without crf.

**Comment by Sucran** [comment]
@Xavierman it is not the results of DSS, you can check it by run their test code.

**Comment by houqb** [comment]
Thanks for your efforts on this. I will check it.
