### ISSUE TITLE
the test performance is inconsistent with the result in paper

### ISSUE THREAD

**Issue by ArcherFMY** [Andrew-Qibin/DSS#2]
Hi, Andrew,

Thank you very much to provide the code to the paper DSS.

I followed the instructions to download the code and the pretrained model. Then I used the provided code `DSS-tutorial.ipynb` to run test on ECSSD dataset. The PR curve I got is even worse than DCL. 

Any idea about what happened? Thank you in advance.

**Comment by houqb** [comment]
Not sure what's going on in your case. Actually the released model is not my initial one, but the results are very close to ones we reported in our paper. Could you show me your results (including Fm and MAE)?

**Comment by ArcherFMY** [comment]
plz see here. https://github.com/ArcherFMY/my-dss-result

the threshold is 2*mean(saliency map)

**Comment by houqb** [comment]
It seems the results you provided are different from mine.
![0001](https://user-images.githubusercontent.com/14296819/28402233-49f43634-6d51-11e7-8d67-75e718027948.png)


Maybe this is due to different versions of Caffe.

**Comment by ArcherFMY** [comment]
I used the newest Caffe version.

Would you mind sharing your caffe? Then I can test again.

**Comment by houqb** [comment]
I have released. You can find it in my another repo.

Kind regards,
Qibin (Andrew)
Homepage: http://mmcheng.net/qbhou/

**Comment by ArcherFMY** [comment]
here is my results...
![selection_003](https://user-images.githubusercontent.com/11482534/28403173-1b168a60-6d56-11e7-9224-507edc44806b.png)

**Comment by houqb** [comment]
good

**Comment by houqb** [comment]
If you average the results from so2, so3, so4, and fusion, the scores would
be better.

Kind regards,
Qibin (Andrew)
Homepage: http://mmcheng.net/qbhou/
