### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by xinyaoguo** [Andrew-Qibin/DSS#20]
I have a question, how much memory do you need to run the code? I try to apply the short connection to other network models, but there are always out of memory errors，I was looking forward to receiving your reply.

**Comment by houqb** [comment]
It actually depends on how many parameters your model has and the size of input images. Short connections themselves do not introduce too many parameters.

**Comment by SayantiBardhan** [comment]
Hi, @xinyaoguo , were you able to solve the memory issue. I am facing the same as well.
@Andrew-Qibin can you comment further on this.
