### ISSUE TITLE
Error while executing run_saliency.py

### ISSUE THREAD

**Issue by sayantanauddy** [Andrew-Qibin/DSS#4]
I am using caffe 1.0.0. I followed the instructions in the DSS readme, but when I try to execute the script run_saliency.py, I am getting the following error:

[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 20:14: **Message type "caffe.ImageDataParameter" has no field named "normalize"**.
F0724 17:51:04.304796 10783 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train_val.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

The error occurs because of line 20 of train_val.prototxt which has `normalize: true`.

Can you please help me in understanding why this happens? Thanks in advance.

**Comment by houqb** [comment]
The input gt image is gray-level, ranging from 0 to 255. However, we need
to normalize it so as to use the cross entropy loss.
You can just solve it by adding a line gt = gt / 255.

Kind regards,
Qibin (Andrew)
Homepage: http://mmcheng.net/qbhou/

**Comment by houqb** [comment]
You may use the Caffe I released in my another repo.

Kind regards,
Qibin (Andrew)
Homepage: http://mmcheng.net/qbhou/

**Comment by sayantanauddy** [comment]
Thank you for replying. I am using [https://github.com/Andrew-Qibin/caffe_dss](caffe_dss) released by you. After building caffe_dss I use the dss folder inside caffe_dss/examples. 

Where should the statement `gt = gt / 255` be added (in which file)? run_saliency.py does not have this variable. The file DSS-tutorial.ipynb has got a variable called `gt` but since it is an object of the class `PIL.PngImagePlugin.PngImageFile`, the statement `gt = gt / 255` cannot be used directly. Running the ipython notebook results in a cuda out-of-memory error "Check failed: error == cudaSuccess (2 vs. 0)  out of memory".

Thanks again for your help.

Best,
Sayantan

**Comment by houqb** [comment]
In the data layer, sigmoid_cross_entropy_loss prefers annotations ranging from 0 to 1, so you need to normalize the groundtruth.

**Comment by xxzcs** [comment]
Hello Qibin, the same error occurs on me, I have added the sentence "gt = gt /255" before/ after the "normalize: true", but another error occurs, which says <"Error parsing text-format caffe.NetParameter: 22:8: Message type "caffe.ImageDataParameter" has no field named "gt">. Is there something wrong? Hope for your help.
