### ISSUE TITLE
Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file

### ISSUE THREAD

**Issue by AirAI** [Andrew-Qibin/DSS#5]
I am using caffe in your github(https://github.com/Andrew-Qibin/caffe_dss). I followed the instructions in the DSS readme. When I executed the `net = caffe.Net('deploy.prototxt', 'dss_model_released.caffemodel', caffe.TEST)` in DSS-tutorial.ipynb, it reported the following error.

I0808 20:35:52.644126    30 net.cpp:255] Network initialization done.
F0808 20:35:52.754325    30 upgrade_proto.cpp:95] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: dss_model_released.caffemodel
*** Check failure stack trace: ***
Aborted (core dumped)

It seems that the caffemodel was not loaded successfully.
Can anyone help me solve this problem?
Thanks.

**Comment by houqb** [comment]
Sorry, I have no idea about your case because of the limited information you provided.

**Comment by Huang-Jin** [comment]
I also found this problem, any idea?
