### ISSUE TITLE
Unknown layer type: ImageLabelmapData 

### ISSUE THREAD

**Issue by gy1874** [Andrew-Qibin/DSS#6]
F0919 09:43:45.324304 18941 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: ImageLabelmapData 
How to fix this problem? hope someone can help me, thanks~

**Comment by houqb** [comment]
You may want my caffe, which includes all you want I think. https://github.com/Andrew-Qibin/caffe_dss
