### ISSUE TITLE
Label image issue

### ISSUE THREAD

**Issue by sayantanauddy** [Andrew-Qibin/DSS#7]
Can the ground truth have pixel values other than 0 and 1 (after normalization)?
After loading the label images using your data layer, I was checking the unique pixel values. For any image the values are always 0 and 1 (normalize=true) even though the label image has values other than 0 and 255.

Does your data layer support only binary label images?

**Comment by houqb** [comment]
You can change the code yourself to adjust it to your own case. For salient object detection, we only care about whether a pixel is salient or not. In fact, any value between 0 and 1 is acceptable.
