### ISSUE TITLE
 Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train_val.prototxt

### ISSUE THREAD

**Issue by Huang-Jin** [Andrew-Qibin/DSS#8]
Hello, when I am using your code in my computer, I found this problem.
When I configured the caffe and run python run_saliency.py in the main directory, this error occured

I1018 16:44:03.186270  3995 solver.cpp:86] Creating training net from train_net file: train_val.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 20:14: Message type "caffe.ImageDataParameter" has no field named "normalize".
F1018 16:44:03.186388  3995 upgrade_proto.cpp:934] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: train_val.prototxt.

I checked the file train_val.prototxt, it had the param 'normalize' like this:
layer {
  name: "data"
  type: "ImageLabelmapData"
  top: "data"
  top: "label"
  include { phase: TRAIN }
  transform_param {
    mirror: true
    mean_value: 104.00699
    mean_value: 116.66877
    mean_value: 122.67892
  }
  image_data_param {
    root_folder: "/opt/dataset/saliency/msra_b/"
    source: "../../data/msra_b/train.lst"
    batch_size: 1
    shuffle: true
    normalize: true
  }
}

Any idea?

**Comment by dpsfigo** [comment]
did you solve this problem? i got the same error.
